name: Deploy to AWS

on:
  push:
    branches:
      - main # Triggers deployment on push to the 'main' branch. Modify as necessary.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify your Python version

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Install EB CLI
        run: |
          pip install awsebcli  # Install Elastic Beanstalk CLI

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Modify as per your region

      #      - name: Deploy to S3
      #        run: |
      #          aws s3 sync . s3://your-s3-bucket-name --exclude ".git/*" --exclude ".github/*"
      - name: Install dependencies
        run: |
          pip install boto3
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application with dependencies
        run: |
          mkdir -p package
          cp -r * package/ || true
          cp -r venv/lib/python3.9/site-packages/* package/ || true
          cd package
          zip -r ../app.zip . || true

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.S3_BUCKET }}/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Create Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name emotion-recognition \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name  Emotion-recognition-qa \
            --version-label ${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
